### ISSUE TITLE
Operation CREATE USER failed 

### ISSUE THREAD

**Issue by vlotho** [vilhelmprytz/pterodactyl-installer#103] opened 2020-10-20 22:28 UTC
**Describe the bug**
creating the mysql user returns an 
```
Package manifest generated successfully.
45 packages you are using are looking for funding.
Use the `composer fund` command to find out more!
Application key set successfully.
* Downloaded pterodactyl panel files & installed composer dependencies!
* Performing MySQL queries..
* Creating MySQL user..
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'pterodactyl'@'127.0.0.1'
```

after several tests, replacing host '127.0.0.1' with 'localhost' fixes the problem.

**To Reproduce**
Steps to reproduce the behaviour:
1. start the installation.
2. fill in all form data.
3. and wait ....

**Expected behaviour**
install successful

**OS (please complete the following information):**
 - OS: Debian 10 Buster
 - Installation: panel

**Additional context**
reinstallation following numerous configuration problems.
the database and the user have been deleted before reinstallation.
the root user does not have a password
I don't really understand, even changing '127.0.0.1' to 'localhost' I still have the error in the install script.
it's ok, i modified the install file to take into account the local files rather than taking the git files.
The pterodactyl account is created correctly.

**Comment by vlotho** [comment] 2020-10-20 23:41
after doing 1 install which ended in failure, because I forgot to delete the ptero conf files in nginx, the mysql error returned:
Application key set successfully.
```
* Downloaded pterodactyl panel files & installed composer dependencies!
* Performing MySQL queries..
* Creating MySQL user..
ERROR 1396 (HY000) at line 1: Operation CREATE USER failed for 'pterodactyl'@'localhost'
```

**Comment by vilhelmprytz** [comment] 2020-10-21 14:57
Did you enter a password? The error you are having would indicate the `FLUSH PRIVILEGES` command was not run but I am a bit unsure.

**Comment by vlotho** [comment] 2020-10-21 17:03
apart from replacing "127.0.0.1" by "localhost" in the install file, I haven't changed anything else.
I did not put a password for the mariadb root account.

**Comment by vilhelmprytz** [comment] 2020-10-21 18:41
> apart from replacing "127.0.0.1" by "localhost" in the install file, I haven't changed anything else.
> I did not put a password for the mariadb root account.

Why did you change this? This may very well be the cause of the problem.

**Comment by vlotho** [comment] 2020-10-21 22:07
I described my approach in the first message.

**Comment by Linux123123** [comment] 2020-10-22 05:37
You know that `sudo` makes you have root privileges yes? If run the script as root it works without a problem. UFW isn't special in any way. You may have a custom debian or something. 

Another thing. localhost should be linked with 127.0.0.1 in your `/etc/hosts` file. It works for other people so it's a problem with your specific install or config.

**Comment by Kieranwest** [comment] 2020-10-27 00:39
Having the same issue.

**Comment by vilhelmprytz** [comment] 2020-10-27 12:03
> Having the same issue.

@Kieranwest Are you also on Debian 10? I'll look into this if several people are having the same issue.

**Comment by Kieranwest** [comment] 2020-10-27 12:06
> > Having the same issue.
> 
> @Kieranwest Are you also on Debian 10? I'll look into this if several people are having the same issue.

Running 18.04. Thankfully, after nuking the machine and then running the script from a console session (not a SSH session) it seemed to go through fine. Happily running Pterodactyl now 👍

**Comment by vlotho** [comment] 2020-10-27 16:54
I am not at home now, I would pick up the thread of this problem on my return on Saturday.

**Comment by vilhelmprytz** [comment] 2020-11-04 19:12
Alright. From what I can gather this is an isolated case, i.e. this is most likely not an issue with the script. The fact that two different people have had the same issue is a bit worrying, perhaps something in the script instructions is not clear enough and has to be rewritten to be more clear or just straight-up broken code.

**Comment by MatteoTHBT** [comment] 2020-11-04 21:02
Hello,
I had the same problem, I don't think I did anything wrong during the instructions and configuration because I was following a tutorial and I did everything like the tutorial it worked on the tutorial, but not me.

Sorry for my bad english, I'm french

**Comment by Linux123123** [comment] 2020-11-07 08:20
@vilhelmprytz I have a feeling that we need to run `mysql_secure_installation` on all the OS's.

**Comment by vlotho** [comment] 2020-11-07 20:08
ok, i'm back.
for the problem with ufw, i am actually not on debian 10 but on the bullseye / sid version.
This is a new installation, as root on ssh.
I just installed ssh, I haven't installed anything else.
The ufw command does not work as root, you must use "sudo".
![Capture d’écran du 2020-11-07 20-58-49](https://user-images.githubusercontent.com/6847623/98450492-60760100-213d-11eb-8905-05108f7f65be.png)

**Comment by vilhelmprytz** [comment] 2020-11-08 02:51
@vlotho I saw you were commenting something here about using Debian `sid`. That distro isn't supported by the script, did you modify the script to make it run in the first place?

**Comment by vlotho** [comment] 2020-11-08 08:27
@vilhelmprytz I actually started by modifying it, but I gave up, there was too much modification to do.
I could also modify my system, but I was afraid of breaking it.
Then, there, I test the script in a vm test, so I reinstalled a buster version.
And then, I don't have much experience in scripting, and what's more, it's frankly not my passion ...

**Comment by vilhelmprytz** [comment] 2020-11-08 12:05
@vlotho Wait, so the issue you reported here occured on a Debian 10 machine?

**Comment by Linux123123** [comment] 2020-11-08 12:09
@vilhelmprytz In support one guy has let me play with his vps which had this problem. He failed 3 times in a row and I made it the first time. 1 We need to make clear that reinstalling is not an option, because then it fails to create a user which already exists. 2 There may be problems with locale that they are using and maybe the password can only be Latin characters.

**Comment by dexter-dz** [comment] 2020-11-21 01:17
same issue repeated for me too...
![image](https://user-images.githubusercontent.com/17889782/99863652-428caf80-2bc5-11eb-8a22-916f49329406.png)
and my machine is Buster : 
![image](https://user-images.githubusercontent.com/17889782/99863675-5801d980-2bc5-11eb-9260-261b0a0f759b.png)

will I have to purge mysql from the system and try this again?

**Comment by dexter-dz** [comment] 2020-11-21 01:37
Before running this script I have manually set a mysql password for root which is blank by default.. should I do some changes to the script?
![image](https://user-images.githubusercontent.com/17889782/99864198-13c40880-2bc8-11eb-8ec2-40d8279a0564.png)

**Comment by vilhelmprytz** [comment] 2020-11-21 17:35
> Before running this script I have manually set a mysql password for root which is blank by default.. should I do some changes to the script?
> ![image](https://user-images.githubusercontent.com/17889782/99864198-13c40880-2bc8-11eb-8ec2-40d8279a0564.png)

@dexter-dz Yes! Did you install MySQL manually before running the script? That won't work. A clean system installation is required before using the script. I wonder, does the installation of MariaDB on Debian prompt users to set their own root password? In that case, it is probably the reason why quite a few problems have had issues on Debian.

**Comment by vlotho** [comment] 2020-11-22 10:51
As far as I'm concerned I was able to successfully install ptero on a vm, I haven't tested it yet on my machine, but anyway the problem only appeared after a failed installation ...

**Comment by vilhelmprytz** [comment] 2020-11-22 15:35
> As far as I'm concerned I was able to successfully install ptero on a vm, I haven't tested it yet on my machine, but anyway the problem only appeared after a failed installation ...

After a failed installation? Do you mind clarifying? :slightly_smiling_face:  The script does not work if you run it twice without reinstalling the OS.

**Comment by vlotho** [comment] 2020-11-22 18:20
Ah ok, I hadn't seen this information on the github. I understand better.
Well, in any case, for the moment it works in vm, I would test again on real machine when I would have found the money to buy me an UPS.

**Comment by vilhelmprytz** [comment] 2020-12-04 22:14
Anything new about this? If people are not having issues anymore, I'll close this.

**Comment by vilhelmprytz** [comment] 2021-01-01 15:52
Closing because of inactivity. Reopen if this is still an issue.

**Closed by vilhelmprytz** 2021-01-01 15:52 UTC
Labels: bug, invalid, question

**Comment by ryrzy** [comment] 2021-02-19 16:29
hi, sorry for opening this but i have that same problem and i can't do fresh install for mariadb, i use few databases there ;) is there a solution to this problem when we have mariadb on server?

**Comment by vilhelmprytz** [comment] 2021-02-19 16:31
No, the script is only meant to be run on clean installs. You can modify the script so it suits your needs :+1:

**Comment by ryrzy** [comment] 2021-02-20 10:56
> No, the script is only meant to be run on clean installs. You can modify the script so it suits your needs

ok i have removed lines with mysql and it worked ;) as db info i have wrote existing db login/pass :) btw you could add an option:

Do you have existing db? (y/N) and if yes go to input login/pass/db :) it is simple as i see :)

**Comment by Linux123123** [comment] 2021-02-20 11:14
No, It is not that simple. The script is meant to run on a clean system **only** as otherwise we would be facing a million other problems. We don't want to support any unsuccessful pterodactyl install systems / databases or users created before installing. In your case for example you would export the databases, reinstall, then run the script on a clean system and import them.

**Comment by ryrzy** [comment] 2021-02-20 11:16
ok, it was only a sugestion ;) thanks and have a nice day

**Comment by psychomanouel10** [comment] 2021-04-09 07:13
i have same problem how can i fix it

**Comment by vilhelmprytz** [comment] 2021-04-09 14:09
> i have same problem how can i fix it

Use the Discord server for support. You are not meant to run the script twice on the same machine without wiping the system first. If you encountered this error even though you're running it on a clean install, open a new issue with additional context.

**Comment by MoonLGH** [comment] 2022-12-06 13:06
i purged mysl and it now working..
```sh
sudo apt-get remove --purge mysql*
```

**Comment by vilhelmprytz** [comment] 2023-02-07 08:46
@gormett This is a very old issue, I doubt any problems you've experienced are caused by the same underlying issues. The uninstall option is available, but in "beta", which is clearly stated. Open a new issue if you suspect you've encountered a new bug in the script.
