### ISSUE TITLE
visually starting but actually already running

### ISSUE THREAD

**Issue by JastinXyz** [vilhelmprytz/pterodactyl-installer#185] opened 2021-05-20 04:48 UTC
when I create a server and try to use it for my discord bot, and the fact is already running but it says in the serve panel it's still starting.

Image: ![click](https://user-images.githubusercontent.com/73673322/118920782-3f4e6280-b961-11eb-8a09-b77413d611dc.png)

**Comment by sinmineryt** [comment] 2021-05-20 06:08
That's not a bug with the script. The issue is with the egg: You need to set the startup message in the egg's configuration.

**Comment by vilhelmprytz** [comment] 2021-05-20 06:41
As mentioned by @sinmineryt, this is not an issue with the script. I would recommend joining the official Pterodactyl Discord for help with Pterodactyl. Closing.

**Closed by vilhelmprytz** 2021-05-20 06:41 UTC
