### ISSUE TITLE
Deamon doesn't start on startup

### ISSUE THREAD

**Issue by Linux1231233** [vilhelmprytz/pterodactyl-installer#56] opened 2020-05-06 11:53 UTC
**Describe the bug**
After installing panel and deamon wings doesnt start normally. It doesnt start the deamon fully (or something like that) and the only solution is to kill wings and start it again

**To Reproduce**
Steps to reproduce the behaviour:
Install panel and deamon on same computer.
Reboot pc.

**Expected behaviour**
It should start on startup normally.

**OS (please complete the following information):**
 - OS: Ubuntu server 18.04.4
 - Installation: panel and deamon

**Additional context**
I see that on github that wings.service file is untested.

**Comment by vilhelmprytz** [comment] 2020-05-06 12:15
The systemd service `wings` is indeed enabled, see [line 318](https://github.com/vilhelmprytz/pterodactyl-installer/blob/master/install-daemon.sh#L318). If it is not starting; make sure you have configured the daemon before restarting the machine. You need to generate the configuration from the panel and put it in the daemon directory.

The "untested" thing you are referring to is the `configs/wings.service` file? Git works like that, it shows the latest commit for a specific commit. If you look closely you will see that the commit is from 2 years ago (when I initially wrote the script) and that the "untested" part is referring to parts of the script which were not finished back then. The systemd service is copied from the pterodactyl installation instructions.

**Comment by Linux1231233** [comment] 2020-05-06 12:46
Yes I have put the configuration from the panel to config directory (if think it would run without it). But the strange thing is that when I kill the wing process which started with systemd and start it from /srv/deamon using npm start it works perfectly.

Also sorry for that misunderstanding of untested in github.

**Comment by vilhelmprytz** [comment] 2020-05-06 13:12
I cannot help you without more information. Most likely this is caused by some configuration issue and not that the script is broken. The Discord server is meant for support.

I'll close this issue now but reopen it if it turns out to be an issue with the script! :smiley: 

Cheers

**Closed by vilhelmprytz** 2020-05-06 13:12 UTC
