### ISSUE TITLE
run development version

### ISSUE THREAD

**Issue by SrBanYT2143** [vilhelmprytz/pterodactyl-installer#339] opened 2022-06-21 20:52 UTC
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

run development version !

**Comment by Linux123123** [comment] 2022-06-22 05:08
Duplicate of #236

**Comment by vilhelmprytz** [comment] 2022-06-27 16:57
Closing because of duplicate (#236).

**Closed by vilhelmprytz** 2022-06-27 16:57 UTC
