### ISSUE TITLE
Failed to create bus connection: No such file or directory

### ISSUE THREAD

**Issue by Erisfiregamer1** [vilhelmprytz/pterodactyl-installer#113] opened 2020-11-12 18:08 UTC
I use goormIDE for my projects, due to it giving root access.
However, when running the panel installer, I get this...

```
* What would you like to do?
* [1] Install the panel
* [2] Install the daemon (Wings)
* [3] Install both on the same machine, i.e. [1] and [2]
* [4] Install 0.7 version of panel (no longer maintained)
* [5] Install 0.6 version of daemon (works with panel 0.7, no longer maintained)
* [6] Install both [4] and [5] on the same machine (daemon script runs after panel)
* Input 1-6: 1
* Retrieving release information..
* Latest version is v1.1.1
######################################################################
* Pterodactyl panel installation script
*
* Copyright (C) 2018 - 2020, Vilhelm Prytz, <vilhelm@prytznet.se>, et al.
* https://github.com/vilhelmprytz/pterodactyl-installer
*
* This script is not associated with the official Pterodactyl Project.
*
* Running ubuntu version 18.04.
######################################################################
* ubuntu 18.04 is supported.
########################################################################
* Database configuration.

* This will be the credentials used for commuication between the MySQL
* database and the panel. You do not need to create the database
* before running this script, the script will do that for you.

* Database name (panel): [-NO-]
* Username (pterodactyl): [-NO-]
* Password (use something strong): [-NO-]
Failed to create bus connection: No such file or directory
```

What's that about?
Goorm uses Apache web servers, maybe that is why...

**Comment by Linux123123** [comment] 2020-11-13 08:43
This error might be related with `dbus` no being installed. I wasn't able to reproduce so can't say much. At that point we only collect information and don't even start installing, so problem is not with installing. Also we only use `nginx` as webserver. And don't really know what you mean about that it uses 'apache` because you should start with a clean machine.

**Comment by Erisfiregamer1** [comment] 2020-11-13 12:21
dbus exsts
When I ran apt install -y dbus it returned dbus was at its latest version

**Comment by Linux123123** [comment] 2020-11-13 14:13
Then it's a problem with your OS / settings and it's isoldated to only you. I can't help much.

**Comment by vilhelmprytz** [comment] 2020-11-13 16:42
`dbus` is most likely not the problem. It should never be missing since all supported distributions come with it pre-installed (unless you're running some strange variant, really dbus is quite essential in most distributions, afaik). Does the error occur after or before the password prompt? I am thinking your error occurs because `timedatectl` is not working, i.e. after the password prompt. Try removing [this line, 914](https://github.com/vilhelmprytz/pterodactyl-installer/blob/master/install-panel.sh#L914), and see if it works. If this is the case, check with your hosting provider. `timedatectl` should work on standard Ubuntu/Debian/CentOS images.

**Comment by Erisfiregamer1** [comment] 2020-11-13 19:08
After the password prompt.
I tried that, same error.
How about this. I'll give YOU root access to see what the heck is going on.

**Comment by vilhelmprytz** [comment] 2020-11-13 20:26
@Erisfiregamer1 When removing the line, I don't expect the script to work since the next prompt will break. I am just trying to determine the cause of the issue. Does the same `dbus` exception message appear once you run the script when it has been modified to not include the line I mentioned earlier?

**Comment by Erisfiregamer1** [comment] 2020-11-13 23:41
Same message yes.

**Comment by chrlew082** [comment] 2020-11-16 18:40
I get the same issue when executing a similar script.

**Comment by vilhelmprytz** [comment] 2020-11-17 15:14
> I get the same issue when executing a similar script.

@chrlew082 A similar script? Do you mind elaborating? If this is a widespread issue, and not related to this goormIDE, it would be great if we could solve it :+1:

**Comment by Erisfiregamer1** [comment] 2020-11-17 18:21
All I could find was that it happened directly after the password input, during setup.
Maybe it;s because I forgot to open the required ports? There is a software built in to the IDE for that.

**Comment by vilhelmprytz** [comment] 2020-12-04 22:15
> All I could find was that it happened directly after the password input, during setup.
> Maybe it;s because I forgot to open the required ports? There is a software built in to the IDE for that.

The ports should not be related. Can you find anything else indicating the cause of the issue?

**Comment by CyberAndrii** [comment] 2021-01-08 21:57
Got this error on Ubuntu 18.4 WSL.
Fixed by running these commands:

```
$ sudo mkdir -p /run/dbus
$ sudo dbus-daemon --system
```

https://github.com/microsoft/WSL/issues/2941#issuecomment-365135535

**Comment by vilhelmprytz** [comment] 2021-01-08 22:10
@CyberAndrii Are you able to run Pterodactyl in WSL? I am not so sure it's going to run at all?

This whole problem is caused by https://github.com/vilhelmprytz/pterodactyl-installer/blob/1799fa3ac0da4361945712b40682929918b72aaf/install-panel.sh#L914 I am working on rewriting this, but generally this error will only appear on installations that aren't going to work anyway.

**Closed** 2021-01-17 22:21 UTC
Labels: invalid, question

**Comment by vilhelmprytz** [comment] 2021-01-17 22:28
Thanks for reporting this. It should now be fixed and will be included in the next release of the script. You can try it out by using the canary version of the script, use option 6 or 8.

**Comment by chrlew082** [comment] 2021-01-17 22:29
I just tried, and it replied with: Could not create bus connection, host is down.

**Comment by vilhelmprytz** [comment] 2021-01-17 22:30
@chrlew082 Did you try the canary version of the script (it's not option 0)? I've seen this occur on WSL so I tried it on WSL and it should be solved.
