### ISSUE TITLE
Add an option to choose which version of pterodactyl panel to install

### ISSUE THREAD

**Issue by sakulmore** [vilhelmprytz/pterodactyl-installer#343] opened 2022-07-12 07:51 UTC
**Describe the solution you'd like**

Add an option to installer to install different versions of pterodactyl panel.

**Comment by Linux123123** [comment] 2022-07-12 07:52
Duplicate of #236

**Comment by vilhelmprytz** [comment] 2022-07-12 12:41
As mentioned by @Linux123123, this is a duplicate issue.

**Closed** 2022-07-12 12:42 UTC
