### ISSUE TITLE
Website offline

### ISSUE THREAD

**Issue by Erani0** [vilhelmprytz/pterodactyl-installer#335] opened 2022-06-18 18:55 UTC
The Website is offline

**Comment by Linux123123** [comment] 2022-06-18 18:55
Duplicate of #334

**Comment by awdojoaidjwad** [comment] 2022-06-19 04:27
when will the website be online again?

**Comment by Linux123123** [comment] 2022-06-19 04:58
In https://status.pterodactyl-installer.se/ there are incident reports with ETR. Also you can run the script by using
```
bash <(curl -s https://raw.githubusercontent.com/vilhelmprytz/pterodactyl-installer/master/install.sh)
```
and choosing canary version of the script.

**Comment by awdojoaidjwad** [comment] 2022-06-19 07:30
> In https://status.pterodactyl-installer.se/ there are incident reports with ETR. Also you can run the script by using
> 
> ```
> bash <(curl -s https://raw.githubusercontent.com/vilhelmprytz/pterodactyl-installer/master/install.sh)
> ```
> 
> and choosing canary version of the script.

Thx Bro :D

**Comment by vilhelmprytz** [comment] 2022-06-19 11:55
This has been fixed as of 10:23 (UTC+2) today.

**Closed by vilhelmprytz** 2022-06-19 11:55 UTC
