### ISSUE TITLE
Host is down

### ISSUE THREAD

**Issue by Nitroc1701** [vilhelmprytz/pterodactyl-installer#136] opened 2021-01-03 11:50 UTC
Hello I have the same issues than last time, Host is down.

**Comment by vilhelmprytz** [comment] 2021-01-03 12:26
What "host is down". Is it https://pterodactyl-installer.se that you are not able to access? It is not down.

Verify that you are able to connect to other websites, like `ping google.com` or `ping pterodactyl-installer.se`.

Duplicate of #126. Closing.

**Closed by vilhelmprytz** 2021-01-03 12:26 UTC
