### ISSUE TITLE
Failed to start pteroq.service

### ISSUE THREAD

**Issue by motoku386** [vilhelmprytz/pterodactyl-installer#170] opened 2021-03-11 10:28 UTC
**Describe the bug**
Ubuntu 18, install-panel.sh
Failed to start pteroq.service: Unit pteroq.service after downloading file pteroq.service
In the file "pteroq.service" should change vars "User" and "Group" from "<user>" to "www-data"(on Ubuntu).

**To Reproduce**
Run the install-panel.sh, set it up to "systemctl start pteroq.service".

**Expected behaviour**
Succesfuly install.
![pterodactil_err](https://user-images.githubusercontent.com/14301402/110772898-cba71f80-8264-11eb-8561-0694f4b46b64.jpg)

**Screenshots**

**OS (please complete the following information):**
 Ubuntu 18
 - Installation: panel

**Additional context**
Add this string after 346 string(for Ubuntu, for other distros may be too)
"sed -i -e "s@<user>@www-data@g" /etc/systemd/system/pteroq.service

**Comment by Linux123123** [comment] 2021-03-11 10:34
This issue is a duplicate of #165. This should have been fixed in #166. It should replace the `<user>` to the corresponding user group to your system. See https://github.com/vilhelmprytz/pterodactyl-installer/blob/7e197813866bbe12ad8e03e9dd15104dff5622a9/install-panel.sh#L449 

I am not sure why this exactly happens to you.

**Comment by vilhelmprytz** [comment] 2021-03-11 10:45
Are you using the latest version of the script (i.e. are you installing the latest version of Pterodactyl or `0.7.x`)?

**Comment by vilhelmprytz** [comment] 2021-05-15 20:09
Stale issue. Reopen if this is still a problem.

**Closed by vilhelmprytz** 2021-05-15 20:09 UTC
