### ISSUE TITLE
Add letsencrypt auto renew support

### ISSUE THREAD

**Issue by Linux123123** [vilhelmprytz/pterodactyl-installer#92] opened 2020-08-29 18:31 UTC
**Is your feature request related to a problem? Please describe.**
Certificates **aren't renewed** automatically, so when they expire the panel breaks.

**Describe the solution you'd like**
Add a **cron** job which runs every so often and check if certificates have expired.
Then if it finds that certificates have expired it **automatically renews** them. 

**Describe alternatives you've considered**
None.

**Additional context**
Preferably this should be done after **#88**

**Comment by vilhelmprytz** [comment] 2020-08-29 18:34
Thank you for reporting this. I would mark this as a duplicate of #88. Auto-renewal is built-in to `certbot` when using `--nginx`. Feel free to add more information to that issue.

**Closed by vilhelmprytz** 2020-08-29 18:34 UTC
