### ISSUE TITLE
No SSL certificate for Daemon-Script

### ISSUE THREAD

**Issue by Hoerli1337** [vilhelmprytz/pterodactyl-installer#57] opened 2020-05-10 15:12 UTC
**Describe the bug**
The installation script of the daemon does not create an SSL certificate.
There is still a query missing, which domain should be used incl. installing the certbot and issuing a certificate.
If you install everything on one system, it works without problems. If you separate panel and daemon, it will not work.

**To Reproduce**
Steps to reproduce the behaviour:
1. Install the Panel on server A
2. Install the Daemon on server B
3. Start the Daemon with the config of the panel
4. Try to connect with ssl

**OS (please complete the following information):**
 - OS: Tested with Debian 9 + 10
 - Installation: daemon

**Additional context**
If i install certbot and create my own ssl-certificate all works fine :)

**Comment by vilhelmprytz** [comment] 2020-05-10 15:21
This is not a bug, this is a new feature request. Are you able to open a new issue as a feature request? I think it's worthy to be requested, so don't disregard it. Closing in favor of new issue.

**Closed by vilhelmprytz** 2020-05-10 15:21 UTC

**Comment by vilhelmprytz** [comment] 2020-05-10 16:24
Closed in favor of #58
